// app/dashboard/remediesDB.ts
export const remediesDB: Record<string, string> = {
  fever: `🌿 Tulsi tea 2–3x daily\n🍎 Warm khichdi\n🧘 Rest\n💊 Tulsi tea 1 cup`,
  headache: `🌿 Sandalwood paste on forehead\n🍎 Light meals\n🧘 Rest in dark room\n💊 Ginger tea 1 cup`,
  nausea: `🌿 Ginger tea\n🍎 Bland foods\n🧘 Slow walks\n💊 Ginger tea small sips`,
  cold: `🌿 Steam inhalation\n🍎 Warm soups\n🧘 Warm compress\n💊 Tulsi tea 1–2 cups/day`,
  cough: `🌿 Honey + ginger\n🍎 Warm broths\n🧘 Steam inhalation\n💊 Honey-lemon 1 tsp 2–3x/day`,
  acidity: `🌿 Aloe vera juice\n🍎 Avoid spicy foods\n🧘 Walk after meals\n💊 Cumin water 1 glass`,
  backpain: `🌿 Sesame oil massage\n🍎 Anti-inflammatory foods\n🧘 Gentle yoga\n💊 Turmeric paste topically`,
  fatigue: `🌿 Ashwagandha milk\n🍎 Light meals\n🧘 Proper sleep\n💊 Ashwagandha milk nightly`,
  insomnia: `🌿 Nutmeg milk\n🍎 Avoid caffeine\n🧘 Meditate before sleep\n💊 Nutmeg milk nightly`,
  stress: `🌿 Brahmi\n🍎 Herbal teas\n🧘 Pranayama\n💊 Brahmi tea 1 cup daily`,
  jointpain: `🌿 Ginger & turmeric paste\n🍎 Anti-inflammatory diet\n🧘 Gentle stretching\n💊 Turmeric paste topically`,
  anemia: `🌿 Beetroot juice\n🍎 Iron-rich foods\n🧘 Light exercise\n💊 Beetroot juice 1 cup`,
  constipation: `🌿 Triphala powder\n🍎 High fiber foods\n🧘 Regular walking\n💊 Triphala 1 tsp at night`,
  diarrhea: `🌿 Pomegranate decoction\n🍎 Light porridge\n🧘 Rest\n💊 Pomegranate decoction small sips`,
  migraine: `🌿 Peppermint oil massage\n🍎 Avoid triggers\n🧘 Rest in dark room\n💊 Brahmi tea 1 cup`,
  acne: `🌿 Neem paste\n🍎 Avoid oily foods\n🧘 Keep skin clean\n💊 Turmeric mask 2–3x/week`,
  eczema: `🌿 Aloe vera gel\n🍎 Avoid spicy foods\n🧘 Moisturize skin\n💊 Aloe vera gel twice daily`,
  thyroid: `🌿 Ashwagandha\n🍎 Iodine-rich foods\n🧘 Light exercise\n💊 Ashwagandha 1 tsp daily`,
  pcos: `🌿 Cinnamon tea\n🍎 Low glycemic foods\n🧘 Yoga & exercise\n💊 Cinnamon tea 1 cup`,
  sinusitis: `🌿 Steam inhalation\n🍎 Warm soups\n🧘 Keep head elevated\n💊 Nasya oil 2 drops`,
  urinaryinfection: `🌿 Dandelion tea\n🍎 Drink water\n🧘 Rest\n💊 Dandelion tea 1 cup`,
  bronchitis: `🌿 Licorice decoction\n🍎 Warm broths\n🧘 Steam inhalation\n💊 Licorice decoction 1 cup`,
  asthma: `🌿 Vasaka leaves\n🍎 Avoid cold foods\n🧘 Breathing exercises\n💊 Vasaka decoction 1 cup`,
  musclecramp: `🌿 Sesame oil massage\n🍎 Hydrate\n🧘 Gentle stretching\n💊 Ashwagandha tonic 1 cup`,
  feverwithcough: `🌿 Tulsi & ginger tea\n🍎 Warm soups\n🧘 Rest\n💊 Tulsi tea 2–3 cups`,
  coldwithsorethroat: `🌿 Licorice tea\n🍎 Warm liquids\n🧘 Steam inhalation\n💊 Licorice tea 1 cup`,
  headachewithnausea: `🌿 Peppermint oil\n🍎 Light foods\n🧘 Rest\n💊 Ginger tea 1 cup`,
  bloating: `🌿 Fennel seeds\n🍎 Avoid beans\n🧘 Gentle walk\n💊 Fennel tea 1 cup`,
  gas: `🌿 Caraway seeds\n🍎 Avoid carbonated drinks\n🧘 Gentle stretching\n💊 Caraway infusion`,
  aciditywithheartburn: `🌿 Aloe vera juice\n🍎 Avoid spicy food\n🧘 Sit upright\n💊 Aloe vera 50 ml`,
  indigestion: `🌿 Ginger tea\n🍎 Light meals\n🧘 Gentle walk\n💊 Ginger tea 1 cup`,
  flatulence: `🌿 Fennel seeds\n🍎 Avoid beans\n🧘 Gentle walks\n💊 Fennel tea 1 cup`,
  vertigo: `🌿 Ginger\n🍎 Light meals\n🧘 Rest\n💊 Ginger decoction 1 cup`,
  dizziness: `🌿 Ashwagandha\n🍎 Hydrate well\n🧘 Sit down\n💊 Ashwagandha tonic`,
  palpitation: `🌿 Arjuna bark decoction\n🍎 Avoid stimulants\n🧘 Rest\n💊 Arjuna tea 1 cup`,
  anxiety: `🌿 Brahmi\n🍎 Herbal teas\n🧘 Meditation\n💊 Brahmi tea 1 cup`,
  depression: `🌿 Ashwagandha\n🍎 Balanced diet\n🧘 Light exercise\n💊 Ashwagandha milk`,
  moodswings: `🌿 Shankhpushpi\n🍎 Fresh fruits\n🧘 Yoga\n💊 Shankhpushpi tea`,
  memoryloss: `🌿 Brahmi\n🍎 Leafy greens\n🧘 Mental exercises\n💊 Brahmi tonic`,
  concentrationissues: `🌿 Brahmi\n🍎 Nuts & seeds\n🧘 Meditation\n💊 Brahmi tea 1 cup`,
  lowenergy: `🌿 Ashwagandha\n🍎 Protein-rich foods\n🧘 Walks\n💊 Ashwagandha milk`,
  hairfall: `🌿 Bhringraj oil massage\n🍎 Protein-rich diet\n🧘 Stress management\n💊 Bhringraj oil`,
  dandruff: `🌿 Neem oil\n🍎 Avoid oily food\n🧘 Wash hair regularly\n💊 Neem oil 2–3x/week`,
  weaknails: `🌿 Amla juice\n🍎 Protein & iron\n🧘 Nail care\n💊 Amla juice 1 cup`,
  skinpigmentation: `🌿 Turmeric mask\n🍎 Hydrate well\n🧘 Sun protection\n💊 Turmeric paste`,
  darkcircles: `🌿 Almond oil massage\n🍎 Hydrate\n🧘 Sleep well\n💊 Almond oil`,
  dryskin: `🌿 Coconut oil massage\n🍎 Drink water\n🧘 Moisturize\n💊 Coconut oil twice daily`,
  oilySkin: `🌿 Neem paste\n🍎 Avoid fried foods\n🧘 Wash face regularly\n💊 Neem paste`,
  rashes: `🌿 Aloe vera gel\n🍎 Avoid spicy foods\n🧘 Keep skin clean\n💊 Aloe vera gel`,
  hives: `🌿 Neem paste\n🍎 Avoid allergens\n🧘 Rest\n💊 Neem paste`,
  allergies: `🌿 Tulsi tea\n🍎 Avoid triggers\n🧘 Rest\n💊 Tulsi tea`,
  asthmaattack: `🌿 Vasaka leaves\n🍎 Avoid cold\n🧘 Breathing exercises\n💊 Vasaka decoction`,
  sinuscongestion: `🌿 Eucalyptus steam\n🍎 Warm liquids\n🧘 Keep head elevated\n💊 Nasya oil`,
  runnynose: `🌿 Tulsi tea\n🍎 Warm fluids\n🧘 Rest\n💊 Tulsi tea`,
  sorethroat: `🌿 Licorice tea\n🍎 Warm liquids\n🧘 Gargle\n💊 Licorice tea`,
  tonsillitis: `🌿 Turmeric milk\n🍎 Soft foods\n🧘 Rest\n💊 Turmeric milk`,
  mouthulcers: `🌿 Licorice paste\n🍎 Avoid spicy foods\n🧘 Oral hygiene\n💊 Licorice paste`,
  gumbleeding: `🌿 Triphala powder\n🍎 Vitamin C foods\n🧘 Gentle brushing\n💊 Triphala`,
  toothache: `🌿 Clove oil massage\n🍎 Soft foods\n🧘 Rest\n💊 Clove oil`,
  coldhandsfeet: `🌿 Ginger tea\n🍎 Warm meals\n🧘 Keep warm\n💊 Ginger tea`,
  numbness: `🌿 Ashwagandha\n🍎 Protein-rich diet\n🧘 Stretching\n💊 Ashwagandha tonic`,
  tingling: `🌿 Ginger\n🍎 Hydrate\n🧘 Gentle stretching\n💊 Ginger tea`,
  cramps: `🌿 Sesame oil massage\n🍎 Hydrate\n🧘 Rest\n💊 Ashwagandha tonic`,
  musclepain: `🌿 Turmeric paste\n🍎 Anti-inflammatory foods\n🧘 Gentle yoga\n💊 Turmeric paste`,
  jointstiffness: `🌿 Ginger & turmeric paste\n🍎 Anti-inflammatory diet\n🧘 Stretching\n💊 Turmeric paste`,
  arthritis: `🌿 Ashwagandha\n🍎 Anti-inflammatory foods\n🧘 Gentle yoga\n💊 Ashwagandha milk`,
  gout: `🌿 Triphala\n🍎 Avoid purine-rich foods\n🧘 Gentle exercise\n💊 Triphala powder`,
  obesity: `🌿 Triphala\n🍎 Light diet\n🧘 Exercise\n💊 Triphala powder`,
  diabetes: `🌿 Bitter gourd juice\n🍎 Low glycemic diet\n🧘 Exercise\n💊 Bitter gourd juice`,
  hypertension: `🌿 Arjuna bark\n🍎 Low salt diet\n🧘 Meditation\n💊 Arjuna decoction`,
  hypotension: `🌿 Licorice\n🍎 Hydrate\n🧘 Rest\n💊 Licorice tea`,
  cholesterol: `🌿 Garlic\n🍎 Low-fat diet\n🧘 Exercise\n💊 Garlic decoction`,
  kidneystones: `🌿 Pomegranate juice\n🍎 Hydrate\n🧘 Rest\n💊 Pomegranate juice`,
  liverproblems: `🌿 Kutki\n🍎 Light diet\n🧘 Rest\n💊 Kutki decoction`,
  jaundice: `🌿 Kutki\n🍎 Hydrate\n🧘 Rest\n💊 Kutki decoction`,
  constipationchronic: `🌿 Triphala\n🍎 Fiber-rich diet\n🧘 Walking\n💊 Triphala 1 tsp`,
  diarrheaacute: `🌿 Pomegranate decoction\n🍎 Light porridge\n🧘 Rest\n💊 Pomegranate decoction`,
  gastritis: `🌿 Aloe vera\n🍎 Bland diet\n🧘 Rest\n💊 Aloe vera juice`,
  ulcers: `🌿 Licorice\n🍎 Bland diet\n🧘 Avoid stress\n💊 Licorice decoction`,
  bloatingchronic: `🌿 Fennel seeds\n🍎 Avoid beans\n🧘 Gentle walks\n💊 Fennel tea`,
  flatulencechronic: `🌿 Caraway seeds\n🍎 Avoid carbonated drinks\n🧘 Gentle stretching\n💊 Caraway tea`,
  indigestionchronic: `🌿 Ginger tea\n🍎 Light meals\n🧘 Gentle walk\n💊 Ginger tea`,
  coldfever: `🌿 Tulsi tea\n🍎 Warm soups\n🧘 Rest\n💊 Tulsi tea`,
  coughfever: `🌿 Honey + ginger\n🍎 Warm broths\n🧘 Steam inhalation\n💊 Honey-lemon`,
  headachefever: `🌿 Peppermint oil\n🍎 Light foods\n🧘 Rest\n💊 Ginger tea`,
  nauseafever: `🌿 Ginger tea\n🍎 Bland foods\n🧘 Rest\n💊 Ginger tea`,
  bodyache: `🌿 Turmeric milk\n🍎 Light meals\n🧘 Rest\n💊 Turmeric milk`,
  chills: `🌿 Ginger tea\n🍎 Warm foods\n🧘 Warm clothing\n💊 Ginger tea`,
  sweating: `🌿 Tulsi tea\n🍎 Hydrate\n🧘 Rest\n💊 Tulsi tea`,
  weakness: `🌿 Ashwagandha\n🍎 Protein foods\n🧘 Light exercise\n💊 Ashwagandha milk`,
  dizzinessfever: `🌿 Ginger tea\n🍎 Light diet\n🧘 Rest\n💊 Ginger tea`,
  dehydration: `🌿 Coconut water\n🍎 Hydrate\n🧘 Rest\n💊 Coconut water`,
  vomiting: `🌿 Ginger tea\n🍎 Bland foods\n🧘 Rest\n💊 Ginger tea`,
  diarrheawithfever: `🌿 Pomegranate decoction\n🍎 Light porridge\n🧘 Rest\n💊 Pomegranate decoction`,
  constipationwithfever: `🌿 Triphala\n🍎 Fiber diet\n🧘 Walking\n💊 Triphala`,
  bodyrash: `🌿 Neem paste\n🍎 Avoid allergens\n🧘 Rest\n💊 Neem paste`,
  itching: `🌿 Aloe vera gel\n🍎 Avoid spicy foods\n🧘 Keep skin clean\n💊 Aloe vera gel`,
  swelling: `🌿 Turmeric paste\n🍎 Anti-inflammatory diet\n🧘 Rest\n💊 Turmeric paste`,
  bruises: `🌿 Arnica massage\n🍎 Light meals\n🧘 Rest\n💊 Arnica paste`,
  cuts: `🌿 Turmeric paste\n🍎 Clean wound\n🧘 Rest\n💊 Turmeric paste`,
  burns: `🌿 Aloe vera gel\n🍎 Avoid hot foods\n🧘 Rest\n💊 Aloe vera gel`,
  insectbites: `🌿 Neem paste\n🍎 Avoid scratching\n🧘 Rest\n💊 Neem paste`,
  headachechronic: `🌿 Brahmi\n🍎 Light diet\n🧘 Meditation\n💊 Brahmi tea`,
  jointpainchronic: `🌿 Ginger & turmeric paste\n🍎 Anti-inflammatory diet\n🧘 Gentle yoga\n💊 Turmeric paste`,
};
